/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_ndk_DecodeYUV */
#include <android/log.h>
#ifndef _Included_com_jni_ndk_DecodeYUV
#define _Included_com_jni_ndk_DecodeYUV
#define LOG_I(FORMAT,...) __android_log_print(ANDROID_LOG_INFO,"C_LOG",FORMAT,__VA_ARGS__)

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_ndk_DecodeYUV
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jni_ndk_DecodeYUV_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
