/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_ndk_FileNative */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <android/log.h>
#ifndef _Included_com_jni_ndk_PosixThread
#define _Included_com_jni_ndk_PosixThread

#define LOG_I(FORMAT,...) __android_log_print(ANDROID_LOG_INFO,"C_LOG",FORMAT,__VA_ARGS__)
#define LOG_E(FORMAT,...) __android_log_print(ANDROID_LOG_ERROR,"C_LOG",FORMAT,__VA_ARGS__)
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_ndk_PosixThread
 * Method:    posixThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_ndk_PosixThread_posixThread(JNIEnv *, jclass);
JNIEXPORT void JNICALL Java_com_jni_ndk_PosixThread_init(JNIEnv *, jclass );
JNIEXPORT void JNICALL Java_com_jni_ndk_PosixThread_destroy(JNIEnv *, jclass );
#ifdef __cplusplus
}
#endif
#endif
