/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_ndk_FileNative */
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <android/log.h>
#ifndef _Included_com_jni_ndk_FileNative
#define _Included_com_jni_ndk_FileNative
#define LOG_I(FORMAT,...) __android_log_print(ANDROID_LOG_INFO,"C_LOG",FORMAT,__VA_ARGS__)
#define LOG_E(FORMAT,...) __android_log_print(ANDROID_LOG_ERROR,"C_LOG",FORMAT,__VA_ARGS__)
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_ndk_FileNative
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_jni_ndk_FileNative_diff
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_jni_ndk_FileNative
 * Method:    merge
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL
Java_com_jni_ndk_FileNative_merge(JNIEnv *, jclass , jstring , jint count,
                                  jstring );

#ifdef __cplusplus
}
#endif
#endif
